name: Deploy

on:
    push:
        branches: [ "main" ]

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build docker image
              run: docker build -t blog-test .
            - name: Deploy over SSH
              uses: appleboy/ssh-action@v1.0.0
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.USER_SERVER }}
                key: ${{ secrets.SSH_PRIVATE_KEY }}
                script: |
                    cd ~
                    git pull
                    docker-compose down
                    docker-compose up -d --build