name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and push docker image
        run: |
          docker build -t blog-test:latest .
          docker save blog-test:latest | gzip > blog-test.tar.gz

      - name: Copy image and deploy
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "blog-test.tar.gz"
          target: "~/tz-blog/"

      - name: Run deploy script on server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/tz-blog
            gunzip -f blog-test.tar.gz
            docker load < blog-test.tar
            docker compose up -d --force-recreate